### ISSUE TITLE
is the latest pep8 brought in on every run?

### ISSUE THREAD

**Issue by sriram-mv** [Bryukh/pep8online#2]

**Comment by Bryukh** [comment]
I'm using pep8 module for this.
Was 1.4.6. Just updated to 1.5.7.
Thanks!

**Comment by sriram-mv** [comment]
It would be great, if it would autoupdate every day, just a suggestion! Great work btw.

**Comment by Bryukh** [comment]
Yep, autoupdate is a good idea. I will add cron job for this.
